<a href="https://colab.research.google.com/github/praveenbunker098-lgtm/45-days-of-python/blob/main/DAY10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Transpose (.T)

Transpose ka matlab hota hai Rows ko Columns me aur Columns ko Rows me convert karna.

In [ ]:
import numpy as np

arr = np.array([[10, 20],
                [30, 40]])

print(np.transpose(arr))

[[10 30]
 [20 40]]


In [ ]:
import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr)
print(arr.T)  #transpose(2,3)---> (3,2)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr.shape)      # (2, 3)
print(arr.T.shape)    # (3, 2)

(2, 3)
(3, 2)


## reshape()

Array ka shape change karta hai.

In [ ]:
import numpy as np

arr = np.arange(1, 7)

print(arr)
new_arr = arr.reshape(2, 3)

print(new_arr)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


## flatten()

2D ya multi-dimensional array ko 1D array me convert karta hai.

## **shorting **

1. short() for 1d
2.

In [ ]:
# sort

# 1d
# import numpy as np
# arr = np.array([10,5,30,470,50,1,7,9])
# print(arr)
# arr_s = np.sort(arr)
# print(arr_s)

# 2d
import numpy as np

arr1 = np.array([[10, 5, 30, 470],
                 [23, 4, 57, 86]])

print(arr1)

arr1_s = np.sort(arr1)
print(arr1_s)

arr1_s_axis0 = np.sort(arr1, axis=0)
print(arr1_s_axis0)

arr1_s_axis1 = np.sort(arr1, axis=1)
print(arr1_s_axis1)

[[ 10   5  30 470]
 [ 23   4  57  86]]
[[  5  10  30 470]
 [  4  23  57  86]]
[[ 10   4  30  86]
 [ 23   5  57 470]]
[[  5  10  30 470]
 [  4  23  57  86]]


In [ ]:
import numpy as np

arr1 = np.array([[10, 5, 30, 470],
                 [23, 4, 57, 86]])

print("Original Array:")
print(arr1)

# Descending row-wise (axis=1)
arr1_desc_axis1 = np.sort(arr1, axis=1)[:, ::-1]
print("\nDescending (axis=1):")
print(arr1_desc_axis1)

# Descending column-wise (axis=0)
arr1_desc_axis0 = np.sort(arr1, axis=0)[::-1]
print("\nDescending (axis=0):")
print(arr1_desc_axis0)

# Descending of all elements
arr1_desc_all = np.sort(arr1, axis=None)[::-1]
print("\nDescending (all elements):")
print(arr1_desc_all)

Original Array:
[[ 10   5  30 470]
 [ 23   4  57  86]]

Descending (axis=1):
[[470  30  10   5]
 [ 86  57  23   4]]

Descending (axis=0):
[[ 23   5  57 470]
 [ 10   4  30  86]]

Descending (all elements):
[470  86  57  30  23  10   5   4]


In [ ]:
import numpy as np

arr1 = np.array([[10, 5, 30, 470],
                 [23, 4, 57, 86]])

print("Original Array:")
print(arr1)

# Ascending row-wise (axis=1)
arr1_asc_axis1 = np.sort(arr1, axis=1)
print("\nAscending (axis=1):")
print(arr1_asc_axis1)

# Ascending column-wise (axis=0)
arr1_asc_axis0 = np.sort(arr1, axis=0)
print("\nAscending (axis=0):")
print(arr1_asc_axis0)

# Ascending of all elements
arr1_asc_all = np.sort(arr1, axis=None)
print("\nAscending (all elements):")
print(arr1_asc_all)

Original Array:
[[ 10   5  30 470]
 [ 23   4  57  86]]

Ascending (axis=1):
[[  5  10  30 470]
 [  4  23  57  86]]

Ascending (axis=0):
[[ 10   4  30  86]
 [ 23   5  57 470]]

Ascending (all elements):
[  4   5  10  23  30  57  86 470]


## *Filter *

  1. array[Expression]
  2. array[array>2] || filter with mask

In [ ]:
# filter

# 1d
import numpy as np
import math

arr = np.array([10, 5, 30, 470, 50, 1, 7, 9])
print(arr)
arr_f = arr[arr < 10]
print(arr_f)

fact_arr = np.vectorize(math.factorial)(arr_f)

print("Elements:", arr_f)
print("Factorials:", fact_arr)

[ 10   5  30 470  50   1   7   9]
[5 1 7 9]
Elements: [5 1 7 9]
Factorials: [   120      1   5040 362880]


Fancy indexing vs np.where()

   1. array(list)
   2. array([0,1,3])
   3. np where (expression) --> ternory operator
   4. np.where(array>2)
  
   5. np.where(array>2, array*2,array)
   6. np.where(array>2, true& false)
  

In [ ]:
#Fancy indexing

# import numpy as np

# arr = np.array([10,20,3,4,90,100])
# print(arr)
# arr_f = arr[[0,2]]# 0 index value , 2 index value
# print(arr_f)



# : 2D Array Row Selection

import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

arr_w = np.where(arr > 2, "True", "False")
print(arr_w)
print(arr[(arr >= 5) & (arr <= 50)])
print(arr[~(arr < 1)])

[['False' 'False' 'True']
 ['True' 'True' 'True']
 ['True' 'True' 'True']]
[5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


## ***Adding or delete data***


   * Add Data → Append, Insert

    * Remove Data → Delete, Filter

    * Join Arrays → Concatenate, Stack

    * Split Arrays → Split

In [ ]:
# Concatenate (2 Arrays Ko Join Karna)
# 1d
# import numpy as np

# arr1 = np.array([10, 20, 30])
# arr2 = np.array([40, 50, 60])

# new_arr = np.concatenate((arr1, arr2))

# print(new_arr)
# arr1_arr2_new = arr1+arr2
# print(arr1_arr2_new)
# print(arr1_arr2_new.sum())

# 2d

import numpy as np

arr1 = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# Concatenate row-wise
new_arr = np.concatenate((arr1, arr2), axis=0)
print("Concatenate (axis=0):")
print(new_arr)

# Element-wise addition
arr1_arr2_new = arr1 + arr2
print("Addition:")
print(arr1_arr2_new)

# Sum of all elements
print("Total Sum:")
print(arr1_arr2_new.sum())


Concatenate (axis=0):
[[10 20 30]
 [40 50 60]
 [ 1  2  3]
 [ 4  5  6]]
Addition:
[[11 22 33]
 [44 55 66]]
Total Sum:
231


## ***static functions***

* np.sum()	Sabhi elements ka sum karta hai


* np.mean() - 	Average nikalta hai
* np.median() - 	Median nikalta hai
* np.std() - 	Standard deviation nikalta hai
* np.var() - 	Variance nikalta hai
* np.sqrt() - 	Square root nikalta hai
* np.power() - 	Power calculate karta hai
* np.abs() - 	Absolute value deta hai
* np.sin() - 	Sine value nikalta hai
* np.cos() - 	Cosine value nikalta hai
* np.tan() - 	Tangent value nikalta hai
* np.log() - 	Natural logarithm nikalta hai
* np.exp() - 	Exponential value nikalta hai

1. np.sum(a) -> Sum of all elements
2. np.mean(a) -> Average = Sum of elements / Number of elements
3. np.median(a) -> Middle value after sorting
4. np.min(a) -> Smallest value in array
5. np.max(a) -> Largest value in array
6. np.var(a) mean,difference,square,average | (sum = ddof) -> divide by array length
7. np.std(a) -> Standard Deviation = √Variance -> Measures spread of data
8. np.prod(a) -> Multiplication of all elements
9. np.cumsum(a) -> Cumulative (running) sum
10. np.cumprod(a) -> Cumulative (running) product
11. np.argmin(a) -> Index position of minimum value
12. np.argmax(a) -> Index position of maximum value
13. np.abs(a) -> Converts negative values to positive -> Absolute value (distance from zero)
14. np.unique(a) -> Returns unique values only -> Removes duplicates
15. np.percentile(a, 50) -> Finds percentage-based value -> 50th percentile = Median
16. np.quantile(a, 0.5) -> Similar to percentile -> 0.5 = 50%
17. np.ptp(a) -> Range = Max - Min
18. np.any(a) -> True if at least one value is True

In [ ]:
import numpy as np

a = np.array([10, 20, 30, 40, 50])

# 1. Sum
print(np.sum(a))

# 2. Mean (Average)
print(np.mean(a))

# 3. Median
print(np.median(a))

# 4. Minimum
print(np.min(a))

150
30.0
30.0
10
