<a href="https://colab.research.google.com/github/praveenbunker098-lgtm/45-days-of-python/blob/main/DAY9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***NumPy***

*   NumPy (Numerical Python) Python ki ek powerful library hai jo arrays aur mathematical operations ke liye use hoti hai. Data Science, Machine Learning, AI, aur Scientific Computing me NumPy bahut use hoti hai.




creating array from list
1. 1d
2. 2d

In [ ]:
import numpy as np
l = [1,2,3]
print(l)


#arr id
def array(arr):
  print(np.array(arr))

array(l)
arr = np.array(l)
print(arr)


#2D array example

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

# print(arr)
# print(arr[0][0])   # 10
# print(arr[1][2])   # 60
# print(arr[2][1])   # 80
# print(arr[1,1])
# print(arr.shape)  #Shape Check Karna
# print(arr[0:3,0])  #specific column ko acces krne k liye
# print(arr[:,0])  #column ko access krne k liye
arr[1,1] = 100
print(arr)


# 2d list example
l = [
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
]
# print(l[0])
# print(l[0][0])
l[1][1]= 100
print(l)

[1, 2, 3]
[1 2 3]
[1 2 3]
[[ 10  20  30]
 [ 40 100  60]
 [ 70  80  90]]
[[10, 20, 30], [40, 100, 60], [70, 80, 90]]


In [ ]:
# list

l = [1,2,3]
lm = l*3
print(lm)

# array
import numpy as np
arr = np.array(l)
print(arr)
lm = 2*arr
print(lm)


[1, 2, 3, 1, 2, 3, 1, 2, 3]
[1 2 3]
[2 4 6]


In [ ]:
# COMPARSION
# LIST
import time
start = time.time()
l = [i*2 for i in range(10000000)]
end = time.time()
print("list output:",end-start)

# ARRAY
import numpy as np
start = time.time()
arr = np.arange(10000000)
arr = arr*2
end = time.time()
print("array output:",end-start)

list output: 0.8504419326782227
array output: 0.052193641662597656


In [ ]:
# ZEROS ARRAY
import numpy as np
arr = np.zeros((3,3,3))
print(arr)


[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
# ones array
import numpy as np
arr = np.ones((3,3,3))
print(arr)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [ ]:
# question
# use of zeros increment by 10 in 2d

import numpy as np
arr = np.zeros((2,5))+10
print(arr)
arr = np.ones((2,5))
print(arr+10)

[[10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]]
[[11. 11. 11. 11. 11.]
 [11. 11. 11. 11. 11.]]


In [ ]:
# full for 1d
import numpy as np
arr = np.full(5,3)
print(arr)

# full in 2d
arr = np.full((2,3),3)
print(arr
      )

[3 3 3 3 3]
[[3 3 3]
 [3 3 3]]


In [ ]:
# question
# by the help of zero -> 2d -> value 6
# by the help of full -> 2d ->value 1

import numpy as np

arr = np.zeros((2, 3))+6

print(arr)


arr = np.full((2,3),1)
print(arr
      )


[[6. 6. 6.]
 [6. 6. 6.]]
[[1 1 1]
 [1 1 1]]


In [ ]:
# RANDOM NUMBER PRINT
import numpy as np
arr  = np.random.random((5))
print(arr)

#in 2D

arr  = np.random.random((2,3))
print(arr)

[0.78381777 0.02717052 0.87850761 0.17806769 0.70075503]
[[0.87520568 0.46284226 0.49841925]
 [0.51314861 0.53306244 0.0987924 ]]


In [ ]:
#arrange for 1d
import numpy as np
arr = np.arange(10)
print(arr)

#arrange for 2d
arr = np.arange(10).reshape(2,5)
print(arr)


#arrange for 3d
arr = np.arange(80).reshape(2,5,8)
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[[ 0  1  2  3  4  5  6  7]
  [ 8  9 10 11 12 13 14 15]
  [16 17 18 19 20 21 22 23]
  [24 25 26 27 28 29 30 31]
  [32 33 34 35 36 37 38 39]]

 [[40 41 42 43 44 45 46 47]
  [48 49 50 51 52 53 54 55]
  [56 57 58 59 60 61 62 63]
  [64 65 66 67 68 69 70 71]
  [72 73 74 75 76 77 78 79]]]


# Vector, Matrix,***bold text*** Tensor

1.   vector(1d)
2.   matrix(2d)
3.  tensor(3d)



In [ ]:
import numpy as np


# vector(1d) list
vector = [10, 20, 30]
print(vector)

# vector(1d) array
import numpy as np
arr = np.array(vector)
print(arr)

#matrix(2d) list
matrix = [
    [1, 2, 3],
    [4, 5, 6]
]
print(matrix)

#matrix(2d) array





# tensor 3d list
tensor = [
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
]
print(tensor)


[10, 20, 30]
[10 20 30]
[[1, 2, 3], [4, 5, 6]]
[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]


# ***Array properties***



1.   shape
2.   dimenson
3.   size
4.   dtype





In [ ]:
# array

import numpy as np
arr = np.arange(12).reshape(3,4)
print("shape:", arr.shape)
print("shape:", np.shape(arr))
print("dimension:", arr.ndim)
print("size:", arr.size)
print("dtype:", arr.dtype)

shape: (3, 4)
shape: (3, 4)
dimension: 2
size: 12
dtype: int64
